### ISSUE TITLE
Futro

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-firmware#29]
Es wäre cool in der Futro $dinge wie die verwendete Hardware oder Firmwareversion bekannt zu geben, aber auch die Anzahl an Router, die daran angeschlossen sind...

**Comment by marchausk** [comment]
futro-fw: firmware/files/www/freifunk/cgi-bin/status
Zeile 57 ersetzen durch:
<h3><% echo -n $(tail -n +3 /sys/kernel/debug/batman_adv/bat0/transtable_local | grep -v P | wc -l) %></h3>
Gibt es in guthub eine eigene Firmware-Sektion für den futro?
Dann gehts zumindest auf der Status-Seite Gruß Marc

**Comment by DO1JLR** [comment]
nevermind, kein Interesse mehr an dem scam
