### ISSUE TITLE
automagischer check: alles okay? alle services online

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-firmware#57]
womöglich wäre ein check ob alle services online sind der alle x minuten läuft keine komplett dumme idee?

**Comment by re4jh** [comment]
so als totmannschalter mit alarmfunktion?
- alle alarmieren? oder wie schaut die reaktion aus?

den vertipper "automagischer check" bitte unbedingt als arbeitstitel behalten!

**Comment by DO1JLR** [comment]
Das automagisch war kein vertipper...

Ich hatte das eher so als internes script erstmal ohne reporting gedacht das selbst und ständig agiert und abgestürtzte dienste, prozesse und was auch immer neu startet oder so was in der art
