### ISSUE TITLE
routen neu aushandeln

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-firmware#59]
wenn der router sich mal für eine route zb zum gateway entschieden hat bleibt er dabei.

auch wenn andere eine bessere priorität usw haben.

wäre gut dass da ein check oder so sich der sache annimmt.

-> auch wenn der ping zum gateway gar nicht mehr geht ein reboot? so als idee?

**Comment by re4jh** [comment]
Sach mal ist das nicht aufgabe des Routingprotokolls tote oder schlechtere routen gegen funktionierende oder gar bessere zu tauschgen?

Dieses Batman spielt das auch zwischen den ff-gateways und den routern ne rolle?
Spannenderweise werden meine Nodes nämlich gerade als "ohne route zum gateway" gezeigt.

Sind aber de facto mit diesem Internet verbunden. 
Man müsste also ein Amnesieprogramm für ausgediente Routen schreiben?

**Comment by DO1JLR** [comment]
**ACHTUNG,** lass dich nicht von der Map beeinflussen.
Was der A.L.F.R.E.D an Daten an die Map gibt hat oft nur ähnlichkeiten mit dem, was der B.A.T.M.A.N. denkt, was im Netz los ist.
Außerdem stellt der neue Meshviewer Informationen nachweisbar falsch da.
**BITTE MAP IGNORIEREN**

Das routingprotokoll setzt stabilität über alles. Und das heißt auch, das er wenn er mal eine Route hat und die nich kaputt geht er die neue bessere route die später dazu gekommen ist leider nicht nimmt.

**Comment by DO1JLR** [comment]
anyway, ist auch egal
