### ISSUE TITLE
Allow remote access button

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-firmware#60]
ein button wäre geil, der unsere ssh pubkeys hinzufügen kann und ssh auf freifunk öffnet für einen management zugang in supportfällen...

 - nicht per default aktiviert
 - einfacher zugang durch "uns" nur durch 1 klick

**Comment by re4jh** [comment]
Könnte sowas helfen?
-> [https://github.com/re4jh/firmware/blob/feature_remote-support-keys/files/www/lan/cgi-bin/sshsupportkeys](https://github.com/re4jh/firmware/blob/feature_remote-support-keys/files/www/lan/cgi-bin/sshsupportkeys)
(Gui-Knopf fehlt noch dazu, Script tut, was es soll)

**Comment by mwarning** [comment]
@re4jh nice, may I use it?

**Comment by re4jh** [comment]
we are currently still discussing the best hosting space aka pubkey space.
and perhaps doing it key by key could be a better solution...
_(a button in the webgui for triggering those functions is still missing, too.)_
of course you are allowed to use this "draft". 
please share your experience with us.

**Comment by mwarning** [comment]
@re4jh I added this: https://github.com/ffulm/firmware/commit/393dd83d1954539e9118a65ef2fa8ad7fc0d32b5

Not quite a support button, but related.

**Comment by mwarning** [comment]
you could put the key on the device and have it enabled by pressing a button.
