### ISSUE TITLE
Save buttons in web config have problems [regression]

### ISSUE THREAD

**Issue by mart-ffbsee** [ffbsee/ffbsee-firmware#76]
Save buttons in web config do save stuff BUT there's no more feedback. The former message "Please reboot" is missing and it to the user it "feels" like the click on "Save" didn't do anything because there's no feedback anymore.
Maybe it has something to do with minifying efforts and putting several .js files into one big .js file

**Comment by re4jh** [comment]
* setText() was prepared and worked properly
* but: some functions were setting this text without using this function.
* now they to. 
* fix was included in https://github.com/ffbsee/ffbsee-firmware/pull/77
* #77 is merged, i close
