### ISSUE TITLE
pulldown menus not working

### ISSUE THREAD

**Issue by DEvil0000** [ffbsee/ffbsee-firmware#82]
pull menus not working for lan ports.

**Comment by re4jh** [comment]
you are talking about those ones to select the desired mode on switch ports?

**Comment by re4jh** [comment]
i am not sure at the moment.
this rebuild_switches() could make sense, but it destroys the preselection that was just made.
so either optimizing this process by saving and restoring the preselection or removing the call for rebuild_switches() from this position are the options.
@mart-ffbsee / @mwarning: what is the better choice ?

**Comment by mwarning** [comment]
I will take a look later.

**Comment by mwarning** [comment]
Where can I find images to reproduce the problem? The current ffbsee images?

**Comment by DEvil0000** [comment]
you can build it like described in the readme. this issue is about current master and there is no official build for it yet.

**Comment by mwarning** [comment]
ok, I can confirm the problem now. It is not present in the FF Ulm firmware. I will compare the code.

**Comment by mwarning** [comment]
I've found the problem. Many instances of == were replaced with === in the ffbsee code (which is a good thing).
But it broke the calls addItem(..., port) and removeItem(..., port) where port is a number.
`port` needs to replaced port.toString() in the these calls to fix the problem.

**Comment by re4jh** [comment]
could be solved now. could somebody please confirm that and close this issue? thx.
